version: "3"

services:
  gitlab:
    image: "yrzr/gitlab-ce-arm64v8:latest"
    # restart: always
    environment:
      # GITLAB_LOG_LEVEL: error
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://pi8.local/gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        nginx['listen_port'] = 80
        pages_external_url 'http://10.15.8.225:81/'
        gitlab_pages['enable'] = true
        gitlab_pages['dir'] = "/var/opt/gitlab/gitlab-pages"
        gitlab_pages['log_directory'] = "/var/log/gitlab/gitlab-pages"
        gitlab_pages['listen_proxy'] = "0.0.0.0:8090"
        gitlab_pages['inplace_chroot'] = true
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "${ADMIN_EMAIL}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['monitoring_whitelist'] = ['127.0.0.0/8', '172.20.0.0/16']
        prometheus['listen_address'] = '0.0.0.0:9090'
        alertmanager['admin_email'] = '${ADMIN_EMAIL}'
        alertmanager['listen_address'] = '0.0.0.0:9093'
        grafana['enable'] = true
        grafana['http_addr'] = '0.0.0.0'
    ports:
      - "81:80"
      - "8090:8090"
      - "843:443"
      - "10022:22"
      - "9092:9090"
      - "9094:9093"
      - "3002:3000"
    volumes:
      - "/home/niunai/gitlab/config:/etc/gitlab"
      - "/home/niunai/gitlab/logs:/var/log/gitlab"
      - "/home/niunai/gitlab/data:/var/opt/gitlab"
    extra_hosts:
      - "pi8.local:10.15.8.225"
    networks:
      gitlab_network:
    healthcheck:
      test: "curl -s -f http:/localhost/gitlab/-/health || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 180s

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/niunai/gitlab/gitlab-runner/config:/etc/gitlab-runner"
    extra_hosts:
      - "pi8.local:10.15.8.225"
    networks:
      gitlab_network:
    depends_on:
      gitlab:
        condition: service_healthy

networks:
  gitlab_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
